# Generated by Django 3.2.4 on 2021-08-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countermatic', '0002_vendor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=50)),
                ('report_code', models.CharField(max_length=5)),
                ('report_str', models.CharField(max_length=5)),
            ],
        ),
    ]
