# Generated by Django 3.2.4 on 2021-08-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countermatic', '0003_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
